.pragma library

// UI strings: English, French, Spanish. `t(lang, key)` falls back to
// English, then to the key itself, so a missing translation never renders
// blank.

var STRINGS = {
  en: {
    tabLive: "Live",
    tabStandings: "Standings",
    tabFollow: "Leagues & Teams",
    tabNotifications: "Notifications",
    heroTitle: "Live Scores",
    upcomingTitle: "Later today",
    noFollowed: "No league followed yet. Pick your leagues and teams in the \"Leagues & Teams\" tab.",
    noLiveMatches: "No live matches right now.",
    selectLeague: "Choose a league",
    noStandings: "Standings unavailable for this league.",
    followedLeagues: "Followed leagues",
    followedTeams: "Followed teams (optional — leave empty to follow the whole league)",
    followedCountries: "Countries to follow (optional — leave empty to track every event)",
    olympicsHelp: "ESPN only exposes Olympic sports individually, and only while that edition's Games are on. Add the ESPN slug for whichever sport is live (e.g. basketball/mens-olympics-basketball), then filter by country below.",
    olympicEventPlaceholder: "Olympic event (ESPN slug)",
    customLeague: "Custom league (ESPN slug, e.g. soccer/fra.1)",
    addLeague: "Add",
    notifMaster: "Enable notifications",
    notifGoals: "Goals",
    notifImportant: "Key moments",
    notifScoreChange: "Score changes",
    notifMatchStatus: "Kickoff / final whistle",
    notifScope: "Scope",
    notifScopeTeams: "Followed teams only",
    notifScopeLeagues: "Any followed league",
    language: "Language",
    idleRefreshRate: "Idle refresh (s)",
    liveRefreshRate: "Live match refresh (s)",
    standingsRefreshRate: "Standings refresh (min)",
    showScoreInBar: "Show score in the bar",
    heroWidgetLabel: "Panel header icon",
    heroWidgetTrophy: "Trophy icon",
    heroWidgetScoreboard: "Score bar / countdown",
    heroKickoffIn: "Kickoff in %1",
    heroKickoffSoon: "Kicking off soon",
    heroVs: "vs",
    footballNameLabel: "Name for this sport",
    footballName_soccer: "Soccer",
    footballName_football: "Football",
    footballName_european_football: "European Football",
    finished: "FINAL",
    removeLeague: "Remove",
    searchPlaceholder: "Search…",
    noOptions: "No options",
    noneSelected: "None selected",
    selectedSuffix: "selected",
    sportGroup_soccer: "Soccer",
    sportGroup_hockey: "Ice hockey",
    sportGroup_basketball: "Basketball",
    sportGroup_football: "American football",
    sportGroup_baseball: "Baseball",
    sportGroup_golf: "Golf",
    sportGroup_racing: "Motorsport",
    sportGroup_mma: "Combat sports",
    sportGroup_olympics: "Olympics"
  },
  fr: {
    tabLive: "Direct",
    tabStandings: "Classements",
    tabFollow: "Ligues & Équipes",
    tabNotifications: "Notifications",
    heroTitle: "Scores en direct",
    upcomingTitle: "À venir aujourd'hui",
    noFollowed: "Aucune ligue suivie. Choisissez vos ligues et équipes dans l'onglet « Ligues & Équipes ».",
    noLiveMatches: "Aucun match en direct pour le moment.",
    selectLeague: "Choisir une ligue",
    noStandings: "Classement indisponible pour cette ligue.",
    followedLeagues: "Ligues suivies",
    followedTeams: "Équipes suivies (optionnel — laissez vide pour suivre toute la ligue)",
    followedCountries: "Pays à suivre (optionnel — laissez vide pour suivre toutes les épreuves)",
    olympicsHelp: "ESPN n'expose les sports olympiques qu'un par un, et seulement pendant les Jeux de l'édition en cours. Ajoutez le slug ESPN du sport en direct (ex. basketball/mens-olympics-basketball), puis filtrez par pays ci-dessous.",
    olympicEventPlaceholder: "Épreuve olympique (slug ESPN)",
    customLeague: "Ligue personnalisée (slug ESPN, ex. soccer/fra.1)",
    addLeague: "Ajouter",
    notifMaster: "Activer les notifications",
    notifGoals: "Buts",
    notifImportant: "Moments importants",
    notifScoreChange: "Changements de score",
    notifMatchStatus: "Coup d'envoi / fin de match",
    notifScope: "Portée",
    notifScopeTeams: "Équipes suivies seulement",
    notifScopeLeagues: "Toute ligue suivie",
    language: "Langue",
    idleRefreshRate: "Rafraîchissement au repos (s)",
    liveRefreshRate: "Rafraîchissement des matchs en direct (s)",
    standingsRefreshRate: "Rafraîchissement des classements (min)",
    showScoreInBar: "Afficher le score dans la barre",
    heroWidgetLabel: "Icône du panneau",
    heroWidgetTrophy: "Icône trophée",
    heroWidgetScoreboard: "Score / compte à rebours",
    heroKickoffIn: "Coup d'envoi dans %1",
    heroKickoffSoon: "Coup d'envoi imminent",
    heroVs: "vs",
    footballNameLabel: "Nom de ce sport",
    footballName_soccer: "Soccer",
    footballName_football: "Football",
    footballName_european_football: "Foot",
    finished: "TERMINÉ",
    removeLeague: "Retirer",
    searchPlaceholder: "Rechercher…",
    noOptions: "Aucune option",
    noneSelected: "Aucune sélection",
    selectedSuffix: "sélectionnées",
    sportGroup_soccer: "Football / Soccer",
    sportGroup_hockey: "Hockey sur glace",
    sportGroup_basketball: "Basketball",
    sportGroup_football: "Football américain",
    sportGroup_baseball: "Baseball",
    sportGroup_golf: "Golf",
    sportGroup_racing: "Sports mécaniques",
    sportGroup_mma: "Sports de combat",
    sportGroup_olympics: "Jeux Olympiques"
  },
  es: {
    tabLive: "En vivo",
    tabStandings: "Clasificación",
    tabFollow: "Ligas y equipos",
    tabNotifications: "Notificaciones",
    heroTitle: "Resultados en vivo",
    upcomingTitle: "Más tarde hoy",
    noFollowed: "Aún no sigues ninguna liga. Elige tus ligas y equipos en la pestaña «Ligas y equipos».",
    noLiveMatches: "No hay partidos en vivo en este momento.",
    selectLeague: "Elegir una liga",
    noStandings: "Clasificación no disponible para esta liga.",
    followedLeagues: "Ligas seguidas",
    followedTeams: "Equipos seguidos (opcional — déjalo vacío para seguir toda la liga)",
    followedCountries: "Países a seguir (opcional — déjalo vacío para seguir todas las pruebas)",
    olympicsHelp: "ESPN solo expone los deportes olímpicos uno por uno, y solo mientras esa edición de los Juegos está en curso. Añade el slug de ESPN del deporte activo (ej. basketball/mens-olympics-basketball) y luego filtra por país abajo.",
    olympicEventPlaceholder: "Prueba olímpica (slug de ESPN)",
    customLeague: "Liga personalizada (slug de ESPN, ej. soccer/fra.1)",
    addLeague: "Añadir",
    notifMaster: "Activar notificaciones",
    notifGoals: "Goles",
    notifImportant: "Momentos clave",
    notifScoreChange: "Cambios de marcador",
    notifMatchStatus: "Inicio / final del partido",
    notifScope: "Alcance",
    notifScopeTeams: "Solo equipos seguidos",
    notifScopeLeagues: "Cualquier liga seguida",
    language: "Idioma",
    idleRefreshRate: "Actualización en reposo (s)",
    liveRefreshRate: "Actualización en vivo (s)",
    standingsRefreshRate: "Actualización de clasificación (min)",
    showScoreInBar: "Mostrar el marcador en la barra",
    heroWidgetLabel: "Icono del panel",
    heroWidgetTrophy: "Icono de trofeo",
    heroWidgetScoreboard: "Marcador / cuenta regresiva",
    heroKickoffIn: "Comienza en %1",
    heroKickoffSoon: "A punto de comenzar",
    heroVs: "vs",
    footballNameLabel: "Nombre de este deporte",
    footballName_soccer: "Fútbol",
    footballName_football: "Football",
    footballName_european_football: "Fut",
    finished: "FINAL",
    removeLeague: "Quitar",
    searchPlaceholder: "Buscar…",
    noOptions: "Sin opciones",
    noneSelected: "Ninguna selección",
    selectedSuffix: "seleccionados",
    sportGroup_soccer: "Fútbol",
    sportGroup_hockey: "Hockey sobre hielo",
    sportGroup_basketball: "Baloncesto",
    sportGroup_football: "Fútbol americano",
    sportGroup_baseball: "Béisbol",
    sportGroup_golf: "Golf",
    sportGroup_racing: "Automovilismo",
    sportGroup_mma: "Deportes de combate",
    sportGroup_olympics: "Juegos Olímpicos"
  }
}

function t(lang, key) {
  var dict = STRINGS[lang] || STRINGS.en
  var value = dict[key]
  if (value === undefined) value = (STRINGS.en[key] !== undefined ? STRINGS.en[key] : key)
  return value
}

// "Soccer" vs "Football" vs "European Football" is a genuine regional
// naming split (not just a translation), so it's its own setting
// (Service.footballName) instead of being tied to the UI language —
// Quebec French commonly says "soccer" the same way English Canada does,
// unlike France French, so language alone can't decide this.
function footballName(lang, pref) {
  return t(lang, "footballName_" + (pref || "soccer"))
}
